export enum ApplicationErrorCode {
  NETWORK_ERROR = 'ERR_NETWORK',
  TIMEOUT_ERROR = 'ERR_TIMEOUT',
  VALIDATION_ERROR = 'ERR_VALIDATION',
  SERVER_ERROR = 'ERR_SERVER',
  UNAUTHORIZED_ERROR = 'ERR_UNAUTHORIZED',
  FILE_TOO_LARGE_ERROR = 'ERR_FILE_TOO_LARGE',
  FILE_TYPE_ERROR = 'ERR_FILE_TYPE',
  UNKNOWN_ERROR = 'ERR_UNKNOWN',
}

export enum HttpStatusCode {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  PAYLOAD_TOO_LARGE = 413,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}